# Site settings
title: "Tomson Qin"
description: "Tomson Qin's resume and projects"

# Google Analytics
google_analytics: G-34SHKZ2GT0

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Tom H. Qin"
resume_title:                   "ANU Graduate"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "tomqin89@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "0435925505"
resume_contact_address:         ""

resume_header_contact_info:     "tomqin89@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>My name is Tom and I'm a statistics and economics graduate from the Australian National University. </p>
<p>I am currently working as a Statistician in Melbourne and as a co founder in a tech business on the side.</p>
<p>The projects you see below is the culmination of my interests in statistics and programming coming together.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/miktab"
#  resume_twitter_url:           "http://twitter.com/Tom60231971"
  resume_dribbble_url:          "http://app.revelian.com/reporting/feedback.cfm?id=282F2DFFCB48B6EAE2C1B1F841E0FB00B14BF7DA1954ACED410AC65EC7CEDFA09AD2A9B5"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/tomson-qin-43bb44190"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "files/resume.pdf"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
